spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=Europe/Moscow
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5463